### ISSUE TITLE
DaggerDiComponent

### ISSUE THREAD

**Issue by mrwilliams** [danprado/easyweather#1]
Getting - Cannot resolve symbol 'DaggerDiComponent' - in the MainApplication when trying to run.

**Comment by danprado** [comment]
Hi @mrwilliams. Could you give more information about the exception? 
Maybe paste the log here, if possible.
Usually, Dagger says why it was not possible to generate the Component.
Thanks.

**Comment by mrwilliams** [comment]
Hi @danprado , thanks for the quick reply. The import for DaggerDiComponent was greyed out and displayed the message when hovering the cursor over it. I cleaned the app a few times and still had the same response. After shutting down, re-opening and cleaning again it now works. Sorry to have bothered you and thanks again for the very useful example.

**Comment by danprado** [comment]
Glad that it worked! 
If you have any questions, let me know. :)
